import ScrollReveal from '../components/ScrollReveal';
import FoldText from '../components/FoldText/FoldText';
import SpotlightCard from '../components/SpotlightCard/SpotlightCard';
import DepthCarousel from '../components/DepthCarousel/DepthCarousel';
import { ABOUT, SKILL_GROUPS } from '../lib/content';
import { PIXEL_PURPLE } from '../lib/theme';
import santaCruz from '../images/about-carousel/santa-cruz.jpg';
import summitLookout from '../images/about-carousel/summit-lookout.jpg';
import trailheadFriends from '../images/about-carousel/trailhead-friends.jpg';
import summitRock from '../images/about-carousel/summit-rock.jpg';
import cardOpening from '../images/about-carousel/card-opening.jpg';
import graduation from '../images/about-carousel/graduation.jpg';
import christmasTree from '../images/about-carousel/christmas-tree.jpg';
import benchPress from '../images/about-carousel/bench-press.webp';
import fishing from '../images/about-carousel/fishing.webp';
import nightOut from '../images/about-carousel/night-out.webp';

/** Generated by scripts/build-about-carousel.mjs, pre-cropped to the 3:4 card. */
const PHOTOS = [
  { image: santaCruz, alt: 'Tony at the UC Santa Cruz entrance sign' },
  { image: summitLookout, alt: 'Sitting on a rocky summit above a wide valley' },
  { image: trailheadFriends, alt: 'Three friends giving thumbs up at a trailhead map' },
  { image: summitRock, alt: 'Resting on a boulder at the top of a mountain trail' },
  { image: cardOpening, alt: 'Opening trading card packs with a friend' },
  { image: graduation, alt: 'In a graduation stole, sitting on the hood of a silver Corvette' },
  { image: christmasTree, alt: 'Sitting with a friend on a giant gift box beneath a lit Christmas tree' },
  { image: benchPress, alt: 'Mid-set on the bench press at the gym, with a spotter standing by' },
  { image: fishing, alt: 'Holding up a crappie caught at the lake' },
  { image: nightOut, alt: 'Walking outside at night in a hoodie' }
];

/** Renders at 280x373: the carousel bottoms out at its 0.4 scale floor in a column this narrow. */
const CARD_WIDTH = 700;
const CARD_HEIGHT = 933;

export default function About() {
  return (
    <div>
      <section className="mx-auto grid max-w-[1100px] gap-10 px-[clamp(24px,6vw,80px)] pb-[90px] pt-[clamp(70px,10vh,110px)] sm:grid-cols-[minmax(180px,240px)_1fr]">
        {/* Centred, shifted left: the deck fans right, toward the bio. */}
        <div className="flex min-h-[420px] -translate-x-[100px] translate-y-[20px] items-center justify-center self-center">
          <DepthCarousel
            items={PHOTOS}
            cardWidth={CARD_WIDTH}
            cardHeight={CARD_HEIGHT}
            // Playground values doubled: 300px at scale 1 there, 240px at 0.4 here.
            radius={80} /* 40 */
            tint={PIXEL_PURPLE}
            depth={260} /* 130 */
            // Past the playground's 45: the Z-shrink eats most of the offset.
            spread={175}
            tilt={0}
            tiltDirection="right"
            // Container-level, so it takes only the 0.8 size difference.
            perspective={800}
            // Three: more reach must clear the bio, and 4-5 sat at the brightness floor.
            visibleCards={3}
            falloff={0.26}
            blur={8} /* 4 */
            duration={200}
            // Dots only; arrows would sit on the card in a column this narrow.
            showControls={false}
            showIndicators
          />
        </div>
        <div>
          {/* h1 for the outline; FoldText renders spans. */}
          <h1 className="mb-5">
            <FoldText
              text="About me"
              splitBy="char"
              hinge="top"
              trigger="mount"
              color="#f2f4fb"
              fontSize="clamp(38px, 5vw, 58px)"
              fontWeight={800}
              className="font-sans"
            />
          </h1>
          {/* On a card, so the background reads behind the bio. */}
          <SpotlightCard
            className="max-w-[640px] rounded-3xl border border-border bg-surface/85 p-[clamp(20px,3vw,32px)] backdrop-blur-md"
            spotlightColor="rgba(111, 116, 232, 0.45)"
          >
            {ABOUT.bio.map((paragraph, i) => (
              <p
                key={i}
                className={`font-sans text-[17px] leading-[1.7] text-white ${i === 0 ? 'mb-4' : ''}`}
              >
                {paragraph}
              </p>
            ))}
          </SpotlightCard>
        </div>
      </section>

      <ScrollReveal className="mx-auto max-w-[1100px] px-[clamp(24px,6vw,80px)] pb-[90px]">
        <h2 className="mb-6 font-sans text-[clamp(24px,2.6vw,30px)] font-extrabold text-ink">Skills &amp; tools</h2>
        <div className="grid gap-6 sm:grid-cols-2">
          {SKILL_GROUPS.map((group) => (
            <SpotlightCard
              key={group.label}
              className="h-full rounded-2xl border border-border bg-surface p-7"
              spotlightColor="rgba(111, 116, 232, 0.45)"
            >
              <div className={`mb-4 font-mono text-xs font-semibold tracking-[0.05em] ${group.accentClass}`}>
                {group.label}
              </div>
              <div className="flex flex-wrap gap-2">
                {group.items.map((item) => (
                  <span
                    key={item}
                    className="inline-block rounded-full bg-pill px-3.5 py-1.5 font-sans text-[13px] font-semibold text-ink-soft transition-transform hover:-translate-y-0.5 hover:bg-accent hover:text-white"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </SpotlightCard>
          ))}
        </div>
      </ScrollReveal>

      <section className="mx-auto max-w-[1100px] px-[clamp(24px,6vw,80px)] pb-[130px]">
        <SpotlightCard
          className="flex flex-wrap items-center justify-between gap-6 rounded-3xl bg-panel p-[clamp(32px,5vw,48px)]"
          spotlightColor="rgba(111, 116, 232, 0.45)"
        >
          <div>
            <h2 className="mb-2 font-sans text-xl font-extrabold text-panel-ink">{ABOUT.resume.heading}</h2>
            <p className="font-sans text-sm text-panel-ink/80">{ABOUT.resume.body}</p>
          </div>
          <a
            href={ABOUT.resume.cta.href}
            // Save it rather than opening a viewer.
            download="Tony-Yu-Resume.pdf"
            className="whitespace-nowrap rounded-full bg-panel-ink px-[26px] py-[13px] font-sans text-sm font-bold text-panel no-underline transition-colors hover:bg-accent hover:text-white"
          >
            {ABOUT.resume.cta.label}
          </a>
        </SpotlightCard>
      </section>
    </div>
  );
}
